services:
  db:
    image: 'mysql:8.0'
    container_name: teahouse-db
    restart: always
    environment:
      MYSQL_DATABASE: TeahouseAcademy
      MYSQL_USER: Admin
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data: