spring:
  profiles:
    active: dev


  docker:
    compose:
      enabled: false
  application:
    name: teahouse-academy

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/TeahouseAcademy
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
      default_batch_fetch_size: 100
    show-sql: true

  flyway:
    enabled: true

  servlet:
    multipart:
      max-file-size: 250MB
      max-request-size: 500MB

gg:
  jte:
    developmentMode: true
    precompiled: false
    templateLocation: src/main/resources/jte

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  max-file-size-mb: 250