spring:
  docker:
    compose:
      enabled: false
  application:
    name: teahouse-academy

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/TeahouseAcademy
    username: Admin
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

gg:
  jte:
    developmentMode: true
    precompiled: false
    templateLocation: src/main/resources/jte